// <auto-generated />
namespace MyVirtualClinicWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StringforImageneedstobelong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StringforImageneedstobelong));
        
        string IMigrationMetadata.Id
        {
            get { return "201704041616211_String for Image needs to be long"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
