// <auto-generated />
namespace MyVirtualClinicWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DefineImageModelImageIdasKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefineImageModelImageIdasKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201703011017085_Define ImageModel.ImageId as [Key]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
